### ISSUE TITLE
Using Open Design

### ISSUE THREAD

**Issue by hazem3500** [storybookjs/addon-designs#124]
So I've seen [Open Design](https://opendesign.dev/) recently and I thought it could be a good fit for this addon.

It will allow us to view multiple design file formats and extract useful data that we couldn't do before.
There is also something called an [Octopus Inspector](https://opendesign.dev/docs/octopus-inspector) that lets you inspect design files directly by embedding them.

**Comment by pocka** [comment]
It seems the project is ongoing but still not ready to use. Also, status and timeline/milestone is unclear.

- [C++ (WASM / Native) rendering engine?](https://github.com/opendesigndev/open-design-engine)
- [Node.js / Browser wrapper for the engine](https://github.com/opendesigndev/open-design-framework)

In addition to this situation, this comment from an employee of Ceros (the company bought the original OpenDesign team) made me think the possibility of the View feature being available in the future would be extremely low.

https://github.com/opendesigndev/open-design-sdk/discussions/38#discussioncomment-4603684

> >  We do not create open source software and do not have plans on making Inspect, or any other Ceros product, open sourced
> 
> While we don’t plan to open source any products, we’re definitely still planning to open source tools that can be used to build products - like Open Design v2. Sorry about the confusion - we didn’t share this information properly with the customer support team.

Closing for now.
