### ISSUE TITLE
Design tab not available @storybook/vue3": "^6.5.6 with storybook-addon-designs": "^6.3.1

### ISSUE THREAD

**Issue by lexguru1** [storybookjs/addon-designs#168]
### Affected design types

- [X] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

Hi all,

I have "@storybook/vue3": "^6.5.6" installed and now i npm'd "storybook-addon-designs": "^6.3.1". I have registered this addon in .storybook/main.js, imported { withDesign } in the story, added the decorators: [with design] and parameters to the export default but the Design tab is not appearing in my browser. I have tried incognito mode also. Do you have any suggestions on why is this not working for me?

Later edit: tried following setup also -  "@storybook/vue3": "^6.5.10" with "storybook-addon-designs": "^7.0.0-alpha.2".

Best,
Alex

### How to reproduce the bug?

"@storybook/vue3": "^6.5.6" installed and now i npm'd "storybook-addon-designs": "^6.3.1". I have registered this addon in .storybook/main.js, imported { withDesign } in the story, added the decorators: [with design] and parameters to the export default but the Design tab is not appearing in my browser.

### Expected behaviour

Design tab available

### Environment

- [X] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

@storybook/vue3": "^6.5.6

### Storybook versions

storybook-addon-designs": "^7.0.0-alpha.2"

**Comment by MineDrum** [comment]
I'm having the same issue, how did you fix it?
