### ISSUE TITLE
Support SB7 

### ISSUE THREAD

**Issue by yarinsa** [storybookjs/addon-designs#191]
**Is your feature request related to a problem? Please describe.**
Yes. We are starting a new design system based on SB7, which will be stable in the next few weeks. When can we expect support?

**Describe the solution you'd like**
Upgrade to the new adding api

**Describe alternatives you've considered**
None.

**Comment by byjokese** [comment]
Same Here, testing the pre-release version of the final v7.0.0, and many add-ons broke as the plugin API changed.

Interested in the new update for addon-designs.

**Comment by Codex-** [comment]
We've been using https://github.com/storybookjs/addon-designs/releases/tag/v7.0.0-beta.2 successfully, would be great to see a stable release though :)

**Comment by byjokese** [comment]
Yep, did not see the beta, with the `beta.2` works perfectly.

**Comment by Codex-** [comment]
If you encounter this:
```
▲ [WARNING] Calling "copy" will crash at run-time because it's an import namespace object, not a function [call-import-namespace]

    node_modules/@figspec/components/esm/es2015/FigspecViewer/InspectorView/InspectorView.js:62:42:
      62 │               ${CopyIcon({ onClick: () => copy(node.characters) })}
         ╵                                           ~~~~

  Consider changing "copy" to a default import instead:

    node_modules/@figspec/components/esm/es2015/FigspecViewer/InspectorView/InspectorView.js:2:7:
      2 │ import * as copy from "copy-to-clipboard";
        │        ~~~~~~~~~
        ╵        copy
```

Then remove `storybook-addon-designs` (and anything else showing as an importer via `npm ls @figspec/components`), perform an `npm i`, then add it back, and `npm i` again. This should bump the lock version, which resolves the error upstream. Or add `@figspec/components` as a dep@latest then remove it again :)

**Comment by mayerraphael** [comment]
Does not work with 7.0.7. getChannel() is not defined error.

**Comment by immanual-tsw** [comment]
Hi,
I am getting this warning while installing storybook-addon-designs.

"Attention: We've detected that you're using the following addons in versions which are known to be incompatible with Storybook 7:
- storybook-addon-designs@6.3.1
Please be aware they might not work in Storybook 7. Reach out to their maintainers for updates

**Comment by pocka** [comment]
WIP #192

**Comment by thafryer** [comment]
Hi Everyone! We have released a new version of the addon. We also changed the package name for the addon, `@storybook/addon-designs`. Please follow instructions from the [readme](https://github.com/storybookjs/addon-designs/blob/master/README.md) to get going with the latest version.
