### ISSUE TITLE
Add support for type: 'markdown'

### ISSUE THREAD

**Issue by blowsie** [storybookjs/addon-designs#193]
**Is your feature request related to a problem? Please describe.**
Add support for `type: 'markdown'`

**Describe the solution you'd like**
An additional `type` to allow markdown files

**Describe alternatives you've considered**
This would be a good replacement for the now deprecated addon-notes

**Design types**

- [ ] `figma`
- [ ] `figspec`
- [ ] `link`
- [ ] `image`
- [ ] `iframe`
- [x] `markdown`

**Additional context**

Proposed API
```
export const myStory = () => <MyComponent />;
impot myDesignNotes from './design-notes.md?raw'

myStory.parameters = {
  design: {
    type: "markdown",
    contents: myDesignNotes,
  },
};
```

**Comment by pocka** [comment]
Why not Docs addon?

While I agree the Docs Addon does not provide completely 1-to-1 feature parity and there could be a room for improvements, this feature is not aligned with the goal of this addon: Display design specs alongside Story for *better design-development workflow* (hopefully).

If you felt the Docs Addon missing a feature, I suggest you [open](https://github.com/storybookjs/storybook/issues/new/choose) a feature request or discussion thread. 
Or, if the core concept of the Docs Addon is not suited for your workflow, creating your own addon (no need to publish) would be the best approach IMO.
