### ISSUE TITLE
storybook 7. 0.12 not working with storybook-addon-designs@6.3.1

### ISSUE THREAD

**Issue by immanual-tsw** [storybookjs/addon-designs#194]
When I try to run the storybook, it is showing that - 
" Attention: We've detected that you're using the following addons in versions which are known to be incompatible with Storybook 7:
- storybook-addon-designs@6.3.1"

I was unable to give previous versions of SB to try if this works with that. 

Please help me out.

Thank you!

**Comment by mtirimie1** [comment]
Is there any update on whether or not this will get updated? This is currently my only package with a conflict

**Comment by pocka** [comment]
Duplicate of #191.
