### ISSUE TITLE
Warning in console after installing addon

### ISSUE THREAD

**Issue by markokos01** [storybookjs/addon-designs#204]
### Affected design types

- [ ] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

I get the warning in the console after I added addon in main.ts.

`Warning: render: key is not a prop. Trying to access it will result in undefined being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)
`

### How to reproduce the bug?

1. Install @storybook/addon-designs
2. Add addon to main.ts
3. Run storybook

### Expected behaviour

I do not expect any errors in console.

### Environment

- [X] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

7.0.1

### Storybook versions

7.2.1

**Comment by mayerraphael** [comment]
Problem is the register Method:

```
...
 else {
            addons.addPanel(PanelName, {
                title: title,
                paramKey: ParameterName,
                render: function (_a) {
                    var active = _a.active, key = _a.key;  // This line here.
                    return (jsx(AddonPanel, { key: key, active: !!active },
                        jsx(ErrorBoundary, null,
                            jsx(Wrapper, { active: !!active }))));
                },
            });
        }
    });
...
```

**Comment by pocka** [comment]
Upstream bug.
https://github.com/storybookjs/storybook/issues/23782
