### ISSUE TITLE
V7 release in npm

### ISSUE THREAD

**Issue by FRITS-Kh** [storybookjs/addon-designs#209]
### Affected design types

- [ ] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

npm still has the `6.3.1` current version.
The `7` version should be released.

### How to reproduce the bug?

https://www.npmjs.com/package/storybook-addon-designs?activeTab=versions

### Expected behaviour

The current npm version matches the GitHub version.

### Environment

- [ ] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

7.0.0

### Storybook versions

7.2.1

**Comment by lpoulter-gradle** [comment]
I think this is still an issue npm is showing latest as 6.3.1 and no mention of 7.0.4 which is the latest tag.
```
storybook-addon-designs@6.3.1 | MIT | deps: 1 | versions: 47
Storybook addon for embedding your design preview in addon panel
https://github.com/pocka/storybook-addon-designs

keywords: storybook-addon, design, figma

dist
.tarball: https://registry.npmjs.org/storybook-addon-designs/-/storybook-addon-designs-6.3.1.tgz
.shasum: 3505a08fdb5a755c970c047470749622db52a1cc
.integrity: sha512-QCHZp4KuUikOq52MPiMfU8QifYTfhHar5vWlbcfkFDz1YrgGMy+QAEt5Y3Vdnffl4GKSK1lAsLuvTuzqTBRvnw==
.unpackedSize: 95.1 kB

dependencies:
@figspec/react: ^1.0.0

maintainers:
- pockawoooh <pockawoooh@gmail.com>

dist-tags:
alpha: 7.0.0-alpha.3  beta: 7.0.0-beta.2    latest: 6.3.1
```
