### ISSUE TITLE
Support for storybook 7

### ISSUE THREAD

**Issue by ArturoDucasse** [storybookjs/addon-designs#218]
**Is your feature request related to a problem? Please describe.**
Currently can't use the addon with Storybook 7.

**Describe the solution you'd like**
Support for Storybook 7.

**Comment by ontoneio** [comment]
+1 on this.

**Comment by sw0ok** [comment]
+1

**Comment by Christofon** [comment]
+1

**Comment by yannbf** [comment]
Hey @ArturoDucasse and everyone watching this issue, this addon changed from `storybook-addon-designs` to `@storybook/addon-designs` and alongside with that change, the support for Storybook 7. The documentation was also updated to reflect the new package.

Please use `@storybook/addon-designs` instead and things should work as intended!

**Comment by Philzen** [comment]
> this addon changed from storybook-addon-designs to @storybook/addon-designs

Great to see @pocka's project became part of the official Storybook ecosystem. IMHO it may be worthwhile adding the information regarding the above change to the README.md, to avoid friction or confusion for people upgrading their addons as part of a Storybook upgrade (such as myself, luckily i found this issue).
