### ISSUE TITLE
Can't use @storybook/addon-designs with NEXTjs 13

### ISSUE THREAD

**Issue by TsengTofu** [storybookjs/addon-designs#219]
### Affected design types

- [X] figma
- [X] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

Packages manage tool: [pnpm](https://pnpm.io/zh-TW/)
With React Framework: [NEXT.js](https://nextjs.org/)  version:   `next: ^13.4.3`
Storybook version: `storybook: ^7.5.3`
Use this addons: [@storybook/addon-designs/](https://storybook.js.org/addons/@storybook/addon-designs/) version: `storybook-addon-designs: ^6.3.1`

I've followed the [docs](https://storybookjs.github.io/addon-designs/?path=/story/docs-quick-start--page):
But still not get the expect result, all I got is:
1. In terminal => `pnpm storybook`
2. Go to the local link to check the result
3. See this:
<img width="1208" alt="image" src="https://github.com/storybookjs/addon-designs/assets/20785029/d1aa518d-f3a0-4d91-a337-3eba05347045">

### How to reproduce the bug?

I've followed the [docs](https://storybookjs.github.io/addon-designs/?path=/story/docs-quick-start--page):
But still not get the expect result, all I got is:
1. Create a NEXT.js project and install storybook
2. Choose any component to add stories
3. Followed the [docs](https://storybookjs.github.io/addon-designs/?path=/story/docs-quick-start--page) to do all steps
4. In terminal => `pnpm storybook`
5. Go to the local link to check the result
6. See this:
<img width="1208" alt="image" src="https://github.com/storybookjs/addon-designs/assets/20785029/d1aa518d-f3a0-4d91-a337-3eba05347045">

I'm pretty sure that the bug can be reproduce.
Please help, thank you.

### Expected behaviour

On the right side, I will have a design panel and show the linked Figma design component.
![image](https://github.com/storybookjs/addon-designs/assets/20785029/c442182a-6a27-49f1-a712-39ec24c9eadc)

### Environment

- [ ] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [X] Other

### Affected versions

^6.3.1

### Storybook versions

^7.5.3

**Comment by pocka** [comment]
The package name has been changed from `storybook-addon-designs` to `@storybook/addon-designs` from v7.
The current online doc (GHPages) is not updated to the latest version (v7).
Refer to [`README.md`](https://github.com/storybookjs/addon-designs/blob/master/README.md) for the time being.

I don't know about Next.js + Storybook integration stuff but looking at your versions and the error message, it should work on the latest version of the addon.

**Comment by TsengTofu** [comment]
> The package name has been changed from `storybook-addon-designs` to `@storybook/addon-designs` from v7. The current online doc (GHPages) is not updated to the latest version (v7). Refer to [`README.md`](https://github.com/storybookjs/addon-designs/blob/master/README.md) for the time being.
> 
> I don't know about Next.js + Storybook integration stuff but looking at your versions and the error message, it should work on the latest version of the addon.

## Pocka, thank you 🙌🏻
According to your answer, I do this to get what I want.
**`main.js` => the storybook setting file**
```javascript
// change the addon name
addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-onboarding',
    '@storybook/addon-interactions',
    '@storybook/addon-designs',
],
```

**`preview.js` => the docs mentioned steps, as you said might not update**
```javascript
// remove this line
import { withDesign } from 'storybook-addon-designs';
const preview = {
  ...preview,
  // remove this line
  decorators: [withDesign],
};
```

**And in my component story below:**
```javascript
parameters = {
  design: {
    type: 'figspec',
    accessToken: '',
    url: ''
  },
}
```

## Works fine✨✨✨✨✨✨✨
Here is the snapshot for my packages version:
`storybook: ^7.5.3`
Other addons
<img width="343" alt="image" src="https://github.com/storybookjs/addon-designs/assets/20785029/9fa7a27f-1d06-4aaf-a072-ef759bbe0bd4">

Hope it can help other people.
And thanks again, without your hint, I won't get it work.

**Comment by MrSunshyne** [comment]
@pocka Is the "withDesign" decorator no longer required? What was it's purpose? I can't seem to find docs about it.
I see it in an existing codebase, and i'm not sure what I lose by removing it.

**Comment by pocka** [comment]
@MrSunshyne See #144. TL;DR is you don't need the decorator and it has been there for unknown reasons (probably mistake).
