### ISSUE TITLE
Changelog & Git version tags

### ISSUE THREAD

**Issue by Hinton** [storybookjs/addon-designs#220]
### Affected design types

- [ ] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

Currently releases are only published on npmjs.com and the changelog is not kept up to date.

This makes it difficult to identify new functionality and changes without resorting to diffing the git history which is less than optimal. It's also hard to identify which commits are used in the releases since they aren't tagged in git, and no github releases are provided.

I apologies if this would be better of as a discussion, I view it as a bug in the release process hence an issue, but I can also appreciate that it's not technically a defect in the code.

### How to reproduce the bug?

Notice an update on npm, attempt to identify what has changed.

### Expected behaviour

Up to date changelog and tagged git releases.

### Environment

- [ ] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

7.0.7

### Storybook versions

7.3.0

**Comment by pocka** [comment]
https://github.com/storybookjs/addon-designs/blob/369a8897c3204a005ba6e9a4e160a27f3cff4668/packages/storybook-addon-designs/CHANGELOG.md

It seems the CHANGELOG is now recorded in there and [the one at the root](https://github.com/storybookjs/addon-designs/blob/369a8897c3204a005ba6e9a4e160a27f3cff4668/CHANGELOG.md) no longer gets updated. [Release page on GitHub repository](https://github.com/storybookjs/addon-designs/releases) is getting updates too. I guess the change was introduced in #198.

@shilman 
We should mark the old CHANGELOG as obsolete. Renaming to something like `CHANGELOG.v1-6.md` would be good?
Also I believe the up-to-date CHANGELOG file should be at repository root for better discoverability, could you configure the release script to emit the file at the repo root?

**Comment by shilman** [comment]
@pocka thanks for the heads up. I agree with your proposal, let me see what we can do!

**Comment by Hinton** [comment]
Thanks for the updates @pocka and @shilman. The latest version published on npm is 7.0.7, https://www.npmjs.com/package/@storybook/addon-designs, while github releases still marks 7.0.4 as the latest release, which is also the latest git tag. The changelog at https://github.com/storybookjs/addon-designs/blob/master/packages/storybook-addon-designs/CHANGELOG.md stops at 7.0.1.

**Comment by pocka** [comment]
> The latest version published on npm is 7.0.7, https://www.npmjs.com/package/@storybook/addon-designs, while github releases still marks 7.0.4 as the latest release, which is also the latest git tag. The changelog at https://github.com/storybookjs/addon-designs/blob/master/packages/storybook-addon-designs/CHANGELOG.md stops at 7.0.1.

@shilman Do you have any idea on this version mismatch? Tooling issue?
Having npm versions not existing on source control (tags) could sound suspicious to users...

**Comment by shilman** [comment]
@pocka it looks like merges to `master` are causing releases to be published but for some reason unable to write back to github due to a permissions issue. you can see it in the log here:

https://github.com/storybookjs/addon-designs/actions/runs/7059456877/job/19217051455

I'll look into what's going wrong this week.

**Comment by shilman** [comment]
Ok, I fixed the release flow and published 7.0.9. Unfortunately the GH release for 7.0.9 contains all the changes from 7.0.4 to 7.0.9, which is annoying. But moving forward the new releases/changelogs should be correct.
