### ISSUE TITLE
Storybook 8 upgrade

### ISSUE THREAD

**Issue by wweaver** [storybookjs/addon-designs#231]
**Is your feature request related to a problem? Please describe.**
When starting up storybook 8 it states this Addon is out of date.

**Describe the solution you'd like**
It still works though so I'm guessing just need a version release to appease storybook?

**Describe alternatives you've considered**

**Design types**

- [ ] `figma`
- [ ] `figspec`
- [ ] `link`
- [ ] `image`
- [ ] `iframe`

**Additional context**

This is the warning I get.
![image](https://github.com/storybookjs/addon-designs/assets/1482976/ff1fcd06-40d3-454d-b3d2-d6935b7416d7)

Your addon is not listed on https://github.com/storybookjs/storybook/issues/26031 though.

**Comment by JReinhold** [comment]
Thanks. I'm attempting to fix this in #232, but I'm doing quite a big refactor so it would be helpful if you could test the canary release out to ensure that I haven't broken anything in the process. The refactor shouldn't be noticeable to users.

At the time of writing the canary version is `@storybook/addon-designs@8.0.0--canary.232.fa1bc6b.0`, but you can always check the PR description for the most up-to-date version.

**Comment by bourpie** [comment]
Here are my tests 
1. Installation on fresh Storybook 8 beta 👍 
2. Setting params in story
<img width="791" alt="image" src="https://github.com/storybookjs/addon-designs/assets/4865432/acc25778-1341-4634-8b06-689f0919a4c2">
Error:

![image](https://github.com/storybookjs/addon-designs/assets/4865432/9a32e3b3-3655-45a4-bc79-bf3c99313d9d)
